# Environment (to override _config.yml for development env)
_env:
  www_url: http://www.cnpaas.localhost:4567
  dashboard_url: http://dashboard.cnpaas.localhost:3000
  doc_url: http://doc.cnpaas.localhost:4000
  blog_url: http://blog.cnpaas.localhost:4001
  environment: development
